/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-06-15 05:02:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

 String greeting="Welcome to Book Shopping Mall";
	    String tagline ="Welcome to Web Market!"; 
  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB\" crossorigin=\"anonymous\">\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI\" crossorigin=\"anonymous\">\n");
      out.write("	</script>\n");
      out.write("<title>Welcome</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"container py-4\">\n");
      out.write("		<header class=\"pb-3 mb-4 border-bottom\">\n");
      out.write("			<a href=\" ./welcome.jsp\" class = \"d-flex align-items-center text-dark text-decoration-none\">\n");
      out.write("			<!-- <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 640\">\n");
      out.write("			!Font Awesome Free v7.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2026 Fonticons, Inc.\n");
      out.write("			<path d=\"M546.1 96L92.7 96C69.8 96 64 101.9 64 124.9L64 515.1C64 538.4 69.8 544 92.7 544L546.1 544C570.5 544 576 538.8 576 514.3L576 126.2C576 101.6 570.6 96 546.1 96zM242.4 284.3C214.9 264.1 170.3 275.6 158.2 307.7C153.9 318.8 148.9 317.2 140.7 316C131 314.5 123.5 312.8 118.2 310.5C89.4 299.1 126.8 255.2 143.1 246.2C184.2 224.8 226.5 224 268.4 241.4C309.3 258.2 302.9 300.6 302.9 369.9C305.6 395.7 298.6 428.2 312.2 458.7C314.1 463.1 312.6 466.6 309.5 469.4C301.1 476.1 270.2 471.6 262.9 462C261 459.8 261.1 458.4 259 455.8C255.4 451.9 251.7 453.6 247.1 456.8C189.7 493.2 106.8 478.2 100.1 413.5C97 384.2 112.5 356.4 139.7 342.5C177.9 323 251.9 330.7 253.7 311.6C254.8 301.4 251.8 291.5 242.4 284.3zM529.1 506.3C529.1 521.4 518 516.2 511.3 516.2L116.4 516.2C109 516.2 98.2 521 98.6 505.5C99 491.6 109.1 496.4 115.7 496.4C248 496 380.2 496 512.5 496.4C519.3 496.4 529.1 492 529.1 506.3zM532.9 165.8L532.9 456.8C532.9 462.5 532.2 470.7 524.8 470.7C512.4 470.3 497.3 477.8 488.7 465.1C482.9 456.4 480.9 461.1 476.3 463.9C422.9 493.6 348.2 471 331.9 378.7C325.8 345.3 331.2 311.6 347.6 278.7C359.4 254.8 404.5 202.6 483.7 248.2L483.7 177.2C483.7 151 483.6 151 509.7 151C512.8 151 516.3 151.4 519.4 151C529.5 150.2 533 155.4 533 165.3C532.9 165.5 532.9 165.6 532.9 165.8zM481.4 398.1C461.9 445.7 408.5 441.4 391.4 403.3C376.3 370 375.9 335.1 391.8 301.8C408.1 267.7 451.5 266.1 473.3 297C493.9 325.8 488.2 381.6 481.4 398.1zM186.6 433.4C179.1 432.1 153.6 430.1 152.9 405.6C152.5 391.7 160.7 382.6 172.7 379.8C197.1 373.9 222 369.9 246.4 365.1C255.3 363.1 253.8 369.5 254.2 374.6C255.6 407.6 228.1 433.8 186.6 433.4z\"/>\n");
      out.write("			</svg> -->\n");
      out.write("			<span class=\"fs-4\">Home</span>\n");
      out.write("			</a>\n");
      out.write("		</header>\n");
      out.write("	    ");
      out.write("\n");
      out.write("	    <div class=\"p-5 mb-4 bg-body-tertiary rounded-3\">\n");
      out.write("	    	<div class=\"container-fluid py-5\">\n");
      out.write("	    		<h1 class=\"display-5 fw-bold\">");
      out.print(greeting );
      out.write("</h1>\n");
      out.write("	    		<p class=\"col-md-8 fs-4\">BookMarket</p>\n");
      out.write("	    	</div>\n");
      out.write("	    </div>\n");
      out.write("	    <div class=\"row align-items-md-stretch text-center\">\n");
      out.write("	    	<div class=\"col-md-12\">\n");
      out.write("	    		<div class=\"h-100 p-5\">\n");
      out.write("	    			<h3>");
      out.print(tagline );
      out.write("</h3>\n");
      out.write("	    		</div>	\n");
      out.write("	    	</div>\n");
      out.write("	    </div>\n");
      out.write("	    <footer class=\"pt-3 mt-4 text-body-secondary border-top\">\n");
      out.write("	     &copy; BookMarket\n");
      out.write("	    </footer>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
